### ISSUE TITLE
Not list neither report

### ISSUE THREAD

**Issue by amalcg** [ifosch/accloudtant#115]
I tried to get list of my EC2 instances and its reports followed by https://pypi.python.org/pypi/accloudtant/0.1.3.

I tried from Mac and Ubuntu systems,

with Python3, am keep getting this error msg and not sure whats cause this,

#accloudtant list

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/accloudtant", line 22, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/accloudtant", line 14, in price_list
    click.echo(Prices())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/accloudtant/aws/prices.py", line 36, in __init__
    self.output = print_prices(self.prices)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/accloudtant/aws/prices.py", line 92, in print_prices
    for size in sorted(instances[ec2_kind][region].keys()):
KeyError: 'linux'

**Comment by djdarkbeat** [comment]
Similar results here too:

  File "/usr/local/bin/accloudtant", line 22, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/accloudtant", line 19, in report
    click.echo(Reports())
  File "/usr/local/lib/python3.6/site-packages/accloudtant/aws/reports.py", line 54, in __init__
    self.prices = Prices()
  File "/usr/local/lib/python3.6/site-packages/accloudtant/aws/prices.py", line 36, in __init__
    self.output = print_prices(self.prices)
  File "/usr/local/lib/python3.6/site-packages/accloudtant/aws/prices.py", line 92, in print_prices
    for size in sorted(instances[ec2_kind][region].keys()):
KeyError: 'linux'

**Comment by ifosch** [comment]
Certainly, the changes in AWS pricing API caused this problem. I'm working in some other way to get these.
