### ISSUE TITLE
Minimal CLI interface

### ISSUE THREAD

**Issue by ifosch** [ifosch/accloudtant#12]
Provide a command hierarchy to access current features, like:

```
accloudtant print
accloudtant report
```

It should allow common and specific options, following [aws-cli](http://docs.aws.amazon.com/cli/latest/reference/#options) style and naming for them.

**Comment by ifosch** [comment]
This was completed.

**Comment by ifosch** [comment]
This is the help message when no command is specified:

```
❯ bin/accloudtant
Usage: accloudtant [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  print
  report
```

The `print` command runs the current code:

```
❯ bin/accloudtant print
EC2 (Hourly prices, no upfronts, no instance type features):
Type           On Demand    1y No Upfront    1y Partial Upfront    1y All Upfront    3y Partial Upfront    3y All Upfront
-----------  -----------  ---------------  --------------------  ----------------  --------------------  ----------------
m4.large           0.126            0.087                0.074             0.0725                0.05              0.047
...
t2.small           0.026            0.018                0.0176            0.0172                0.0123            0.0115
```

The `report` command is not yet implemented:

```
❯ bin/accloudtant report
Traceback (most recent call last):
  File "bin/accloudtant", line 23, in <module>
    cli()
  ...
  File "bin/accloudtant", line 19, in report
    raise NotImplementedError
NotImplementedError
```
